best_params:
  lookback_days: 90
  min_t_stat: 2.0
  confidence_level: 0.95
  volatility_adjustment: true
param_grid:
  lookback_days:
    max: 180
    min: 60
    step: 15
  min_t_stat:
    max: 3.0
    min: 1.5
    step: 0.25
  confidence_level:
    values: [0.90, 0.95, 0.99]
  volatility_adjustment:
    values: [true, false]
risk:
  max_position: 0.05
  stop_loss: 0.1
  take_profit: 0.2
signal:
  rebalance_freq: daily
  min_observations: 30
  position_scaling: "t_stat"
strategy:
  description: "Cramér-Rao Drift-Significance Filter using statistical significance testing"
  name: drift_significance
  version: '1.0'
