# Variance Ratio Strategy Configuration

strategy:
  name: "variance_ratio"
  description: "Drift vs noise detection using Lo-MacKinlay variance ratio test"
  version: "1.0"

# Parameter grid for hyperoptimization
param_grid:
  lookback_days:
    min: 30
    max: 120
    step: 10
    
  lag_q:
    values: [2, 3, 5, 10, 20]
    
  threshold_delta:
    min: 0.05
    max: 0.25
    step: 0.05
    
  min_z_stat:
    min: 1.5
    max: 3.0
    step: 0.25

# Risk parameters
risk:
  max_position: 0.05  # 5% max position
  stop_loss: 0.10     # 10% stop loss
  take_profit: 0.20   # 20% take profit
  
# Signal parameters
signal:
  rebalance_freq: "daily"
  
# Current best parameters (updated by hyperopt)
best_params:
  lookback_days: 60
  lag_q: 5
  threshold_delta: 0.10
  min_z_stat: 2.0
